# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 535a7d20daaa9bd64bda38ee1aa288437883a3bb13b6a9036181e875cca74ecbd5b4abc5c1b799f5d456541c0e552d88ed172ca18afba0c70a30ba4114c3a945

test:
  secret_key_base: fd5d77967d58fa4cc0a8caaae74c72978c5d74e8a73f359cb92f97e108319e14d320e9f9f0d9afec29edc353eab261cce16c974fe20bda97b4458cbb7ccfa58e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
